#ifndef JINJA_CMETA_INTERNAL_H
#define JINJA_CMETA_INTERNAL_H

#include "jinja_cmeta.h"

#include <stdint.h>
#include <cstl/allocator.h>

int jinja_cmeta_is_builtin_global(vstr name);

#define JINJA_CMETA_EXPRESSION_NAME_PREFIX "@jinja_expr:"
#define JINJA_CMETA_CURRENT_LOOP_NAME "@jinja_current_loop"
#define JINJA_CMETA_MAX_COMPILED_EXPRESSIONS JINJA_CMETA_MAX_CONDITION_BRANCHES

/* Current tstr storage uses 32-bit lengths on LLP64 and may grow to twice the
 * requested length. Keep capacity representable and leave address-space room
 * for its header and terminator; this is a per-string, not per-render bound. */
#define JINJA_CMETA_MAX_TSTR_BYTES \
  ((size_t)(UINT32_MAX / 2u) < SIZE_MAX / 4u ? (size_t)(UINT32_MAX / 2u) : SIZE_MAX / 4u)

static inline int jinja_cmeta_string_append_fits(size_t used, size_t incoming, size_t limit) {
  return used <= limit && incoming <= limit - used &&
      used <= JINJA_CMETA_MAX_TSTR_BYTES && incoming <= JINJA_CMETA_MAX_TSTR_BYTES - used;
}

typedef enum JINJA_CMETA_EXPRESSION_KIND {
  JINJA_CMETA_EXPRESSION_BOOL = 1,
  JINJA_CMETA_EXPRESSION_INTEGER,
  JINJA_CMETA_EXPRESSION_FLOAT,
  JINJA_CMETA_EXPRESSION_STRING,
  JINJA_CMETA_EXPRESSION_NONE,
  JINJA_CMETA_EXPRESSION_PATH,
  JINJA_CMETA_EXPRESSION_CALL,
  JINJA_CMETA_EXPRESSION_MACRO,
  JINJA_CMETA_EXPRESSION_BLOCK,
  JINJA_CMETA_EXPRESSION_SELF,
  JINJA_CMETA_EXPRESSION_MODULE,
  JINJA_CMETA_EXPRESSION_CAPTURE,
  JINJA_CMETA_EXPRESSION_ITEM_LOOKUP,
  JINJA_CMETA_EXPRESSION_SLICE_LOOKUP,
  JINJA_CMETA_EXPRESSION_CONCAT,
  JINJA_CMETA_EXPRESSION_LENGTH,
  JINJA_CMETA_EXPRESSION_DEFAULT,
  JINJA_CMETA_EXPRESSION_FIRST,
  JINJA_CMETA_EXPRESSION_LAST,
  JINJA_CMETA_EXPRESSION_ABS,
  JINJA_CMETA_EXPRESSION_TO_INT,
  JINJA_CMETA_EXPRESSION_TO_FLOAT,
  JINJA_CMETA_EXPRESSION_ROUND,
  JINJA_CMETA_EXPRESSION_FILESIZEFORMAT,
  JINJA_CMETA_EXPRESSION_FORMAT,
  JINJA_CMETA_EXPRESSION_WORDCOUNT,
  JINJA_CMETA_EXPRESSION_WORDWRAP,
  JINJA_CMETA_EXPRESSION_UPPER,
  JINJA_CMETA_EXPRESSION_LOWER,
  JINJA_CMETA_EXPRESSION_CAPITALIZE,
  JINJA_CMETA_EXPRESSION_TITLE,
  JINJA_CMETA_EXPRESSION_URLENCODE,
  JINJA_CMETA_EXPRESSION_XMLATTR,
  JINJA_CMETA_EXPRESSION_TO_STRING,
  JINJA_CMETA_EXPRESSION_SAFE,
  JINJA_CMETA_EXPRESSION_ESCAPE,
  JINJA_CMETA_EXPRESSION_FORCEESCAPE,
  JINJA_CMETA_EXPRESSION_TRIM,
  JINJA_CMETA_EXPRESSION_CENTER,
  JINJA_CMETA_EXPRESSION_INDENT,
  JINJA_CMETA_EXPRESSION_TRUNCATE,
  JINJA_CMETA_EXPRESSION_REVERSE,
  JINJA_CMETA_EXPRESSION_BATCH,
  JINJA_CMETA_EXPRESSION_SLICE_FILTER,
  JINJA_CMETA_EXPRESSION_SUM,
  JINJA_CMETA_EXPRESSION_MIN,
  JINJA_CMETA_EXPRESSION_MAX,
  JINJA_CMETA_EXPRESSION_SORT,
  JINJA_CMETA_EXPRESSION_DICTSORT,
  JINJA_CMETA_EXPRESSION_UNIQUE,
  JINJA_CMETA_EXPRESSION_GROUPBY,
  JINJA_CMETA_EXPRESSION_PPRINT,
  JINJA_CMETA_EXPRESSION_RANDOM,
  JINJA_CMETA_EXPRESSION_STRIPTAGS,
  JINJA_CMETA_EXPRESSION_URLIZE,
  JINJA_CMETA_EXPRESSION_TOJSON,
  JINJA_CMETA_EXPRESSION_JOIN,
  JINJA_CMETA_EXPRESSION_ATTR,
  JINJA_CMETA_EXPRESSION_REPLACE,
  JINJA_CMETA_EXPRESSION_MAP,
  JINJA_CMETA_EXPRESSION_SELECT,
  JINJA_CMETA_EXPRESSION_REJECT,
  JINJA_CMETA_EXPRESSION_SELECTATTR,
  JINJA_CMETA_EXPRESSION_REJECTATTR,
  JINJA_CMETA_EXPRESSION_HOST_FILTER,
  JINJA_CMETA_EXPRESSION_TO_LIST,
  JINJA_CMETA_EXPRESSION_ITEMS,
  JINJA_CMETA_EXPRESSION_ATTRIBUTE_LOOKUP,
  JINJA_CMETA_EXPRESSION_LOOP_CYCLE,
  JINJA_CMETA_EXPRESSION_LOOP_CHANGED,
  JINJA_CMETA_EXPRESSION_LOOP_RECURSE,
  JINJA_CMETA_EXPRESSION_RANGE,
  JINJA_CMETA_EXPRESSION_NAMESPACE,
  JINJA_CMETA_EXPRESSION_CYCLER,
  JINJA_CMETA_EXPRESSION_JOINER,
  JINJA_CMETA_EXPRESSION_CYCLER_NEXT,
  JINJA_CMETA_EXPRESSION_CYCLER_RESET,
  JINJA_CMETA_EXPRESSION_JOINER_CALL,
  JINJA_CMETA_EXPRESSION_DICT_CALL,
  JINJA_CMETA_EXPRESSION_RANGE_COUNT,
  JINJA_CMETA_EXPRESSION_RANGE_INDEX,
  JINJA_CMETA_EXPRESSION_TEST,
  JINJA_CMETA_EXPRESSION_COMPARISON,
  JINJA_CMETA_EXPRESSION_NESTED_COMPARISON,
  JINJA_CMETA_EXPRESSION_COMPARISON_CHAIN,
  JINJA_CMETA_EXPRESSION_UNARY_ARITHMETIC,
  JINJA_CMETA_EXPRESSION_BINARY_ARITHMETIC,
  JINJA_CMETA_EXPRESSION_LOGICAL_AND,
  JINJA_CMETA_EXPRESSION_LOGICAL_OR,
  JINJA_CMETA_EXPRESSION_CONDITIONAL,
  JINJA_CMETA_EXPRESSION_LIST,
  JINJA_CMETA_EXPRESSION_TUPLE,
  JINJA_CMETA_EXPRESSION_DICT
} JINJA_CMETA_EXPRESSION_KIND;

typedef enum JINJA_CMETA_TEST_KIND {
  JINJA_CMETA_TEST_DEFINED,
  JINJA_CMETA_TEST_UNDEFINED,
  JINJA_CMETA_TEST_NONE,
  JINJA_CMETA_TEST_BOOLEAN,
  JINJA_CMETA_TEST_TRUE,
  JINJA_CMETA_TEST_FALSE,
  JINJA_CMETA_TEST_INTEGER,
  JINJA_CMETA_TEST_FLOAT,
  JINJA_CMETA_TEST_NUMBER,
  JINJA_CMETA_TEST_STRING,
  JINJA_CMETA_TEST_MAPPING,
  JINJA_CMETA_TEST_SEQUENCE,
  JINJA_CMETA_TEST_ITERABLE,
  JINJA_CMETA_TEST_CALLABLE,
  JINJA_CMETA_TEST_ESCAPED,
  JINJA_CMETA_TEST_FILTER,
  JINJA_CMETA_TEST_TEST,
  JINJA_CMETA_TEST_ODD,
  JINJA_CMETA_TEST_EVEN,
  JINJA_CMETA_TEST_DIVISIBLEBY,
  JINJA_CMETA_TEST_SAMEAS,
  JINJA_CMETA_TEST_EQUAL,
  JINJA_CMETA_TEST_NOT_EQUAL,
  JINJA_CMETA_TEST_LESS,
  JINJA_CMETA_TEST_LESS_EQUAL,
  JINJA_CMETA_TEST_GREATER,
  JINJA_CMETA_TEST_GREATER_EQUAL,
  JINJA_CMETA_TEST_IN,
  JINJA_CMETA_TEST_HOST
} JINJA_CMETA_TEST_KIND;

typedef enum JINJA_CMETA_OPERAND_KIND {
  JINJA_CMETA_OPERAND_PATH = 1,
  JINJA_CMETA_OPERAND_BOOL,
  JINJA_CMETA_OPERAND_INTEGER,
  JINJA_CMETA_OPERAND_FLOAT,
  JINJA_CMETA_OPERAND_STRING
} JINJA_CMETA_OPERAND_KIND;

typedef enum JINJA_CMETA_COMPARISON_KIND {
  JINJA_CMETA_COMPARISON_EQUAL,
  JINJA_CMETA_COMPARISON_NOT_EQUAL,
  JINJA_CMETA_COMPARISON_LESS,
  JINJA_CMETA_COMPARISON_LESS_EQUAL,
  JINJA_CMETA_COMPARISON_GREATER,
  JINJA_CMETA_COMPARISON_GREATER_EQUAL,
  JINJA_CMETA_COMPARISON_IN,
  JINJA_CMETA_COMPARISON_NOT_IN
} JINJA_CMETA_COMPARISON_KIND;

typedef enum JINJA_CMETA_ARITHMETIC_KIND {
  JINJA_CMETA_ARITHMETIC_POSITIVE,
  JINJA_CMETA_ARITHMETIC_NEGATE,
  JINJA_CMETA_ARITHMETIC_ADD,
  JINJA_CMETA_ARITHMETIC_SUBTRACT,
  JINJA_CMETA_ARITHMETIC_MULTIPLY,
  JINJA_CMETA_ARITHMETIC_TRUE_DIVIDE,
  JINJA_CMETA_ARITHMETIC_FLOOR_DIVIDE,
  JINJA_CMETA_ARITHMETIC_MODULO,
  JINJA_CMETA_ARITHMETIC_POWER
} JINJA_CMETA_ARITHMETIC_KIND;

typedef struct JINJA_CMETA_OPERAND {
  JINJA_CMETA_OPERAND_KIND kind;
  int boolean;
  int64_t integer;
  double floating;
  vstr text;
} JINJA_CMETA_OPERAND;

typedef struct JINJA_CMETA_COMPARISON_STEP {
  JINJA_CMETA_COMPARISON_KIND comparison;
  size_t operand_node;
} JINJA_CMETA_COMPARISON_STEP;

typedef struct JINJA_CMETA_DICT_ENTRY {
  size_t key_node;
  size_t value_node;
} JINJA_CMETA_DICT_ENTRY;

typedef struct JINJA_CMETA_EXPRESSION_NODE {
  JINJA_CMETA_EXPRESSION_KIND kind;
  int boolean;
  int64_t integer;
  double floating;
  vstr string;
  vstr path;
  JINJA_CMETA_OPERAND left;
  JINJA_CMETA_OPERAND right;
  JINJA_CMETA_COMPARISON_KIND comparison;
  JINJA_CMETA_ARITHMETIC_KIND arithmetic;
  JINJA_CMETA_TEST_KIND test;
  size_t left_node;
  size_t right_node;
  size_t test_node;
  size_t first_comparison_step;
  size_t comparison_step_count;
  size_t first_collection_item;
  size_t collection_item_count;
  size_t unary_not_count;
  int merge_expanded_keywords;
  int has_else;
  int force_boolean;
  vstr loop_alias;
  size_t source_offset;
} JINJA_CMETA_EXPRESSION_NODE;

#define JINJA_CMETA_MAX_PROGRAM_BYTES (2u * JINJA_CMETA_MAX_TEMPLATE_BYTES)
#define JINJA_CMETA_MAX_EXPRESSION_STRING_BYTES JINJA_CMETA_MAX_PROGRAM_BYTES

typedef struct JINJA_CMETA_CALL_ARGUMENT {
  size_t value_node;
  size_t name_offset;
  size_t name_length;
  int unpack_kind;
} JINJA_CMETA_CALL_ARGUMENT;

typedef struct JINJA_CMETA_COLLECTION_ITEM {
  size_t value_node;
  int unpack_kind;
} JINJA_CMETA_COLLECTION_ITEM;

typedef struct JINJA_CMETA_PARAMETER {
  size_t name_offset;
  size_t name_length;
  size_t default_expression;
} JINJA_CMETA_PARAMETER;

typedef struct JINJA_CMETA_FUNCTION {
  size_t name_offset;
  size_t name_length;
  size_t first_parameter;
  size_t parameter_count;
  size_t body_begin;
  size_t body_end;
  size_t parent;
  size_t call_expression;
  int uses_caller;
  int accepts_kwargs;
  int accepts_varargs;
  int is_block;
  int scoped;
  int required;
} JINJA_CMETA_FUNCTION;

typedef struct JINJA_CMETA_TRANSLATION_BINDING {
  size_t name_offset;
  size_t name_length;
  size_t expression;
} JINJA_CMETA_TRANSLATION_BINDING;

typedef struct JINJA_CMETA_TRANSLATION {
  size_t singular_offset;
  size_t singular_length;
  size_t plural_offset;
  size_t plural_length;
  size_t context_offset;
  size_t context_length;
  size_t first_binding;
  size_t binding_count;
  int trimmed;
} JINJA_CMETA_TRANSLATION;

typedef enum JINJA_CMETA_OPCODE {
  JINJA_CMETA_OP_TEXT = 1,
  JINJA_CMETA_OP_OUTPUT,
  JINJA_CMETA_OP_IF_FALSE,
  JINJA_CMETA_OP_JUMP,
  JINJA_CMETA_OP_FOR_BEGIN,
  JINJA_CMETA_OP_FOR_NEXT,
  JINJA_CMETA_OP_SCOPE_BEGIN,
  JINJA_CMETA_OP_SCOPE_END,
  JINJA_CMETA_OP_SET,
  JINJA_CMETA_OP_SET_UNPACK,
  JINJA_CMETA_OP_FILTER_BEGIN,
  JINJA_CMETA_OP_FILTER_END,
  JINJA_CMETA_OP_WITH_BEGIN,
  JINJA_CMETA_OP_CAPTURE_BEGIN,
  JINJA_CMETA_OP_CAPTURE_END,
  JINJA_CMETA_OP_AUTOESCAPE_BEGIN,
  JINJA_CMETA_OP_AUTOESCAPE_END,
  JINJA_CMETA_OP_EVALUATE,
  JINJA_CMETA_OP_FUNCTION,
  JINJA_CMETA_OP_BLOCK,
  JINJA_CMETA_OP_LOOP_CONTROL,
  JINJA_CMETA_OP_TRANSLATE
} JINJA_CMETA_OPCODE;

typedef struct JINJA_CMETA_INSTRUCTION {
  JINJA_CMETA_OPCODE opcode;
  size_t offset;
  size_t length;
  size_t target;
  size_t end;
  size_t else_target;
  size_t collection_target;
  size_t collection_count;
  size_t expression;
  size_t depth;
  size_t source_offset;
  int recursive;
  int filtered;
  int collection_unpack;
  int flag;
  char close_char;
} JINJA_CMETA_INSTRUCTION;

#endif
