#ifndef DSV_FILTER_EXPR_PARSER_H
#define DSV_FILTER_EXPR_PARSER_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    DSV_EXPR_ITEM_NUMBER = 1,
    DSV_EXPR_ITEM_IDENT,
    DSV_EXPR_ITEM_ADD,
    DSV_EXPR_ITEM_SUB,
    DSV_EXPR_ITEM_MUL,
    DSV_EXPR_ITEM_DIV,
    DSV_EXPR_ITEM_NEG
} dsv_expr_item_kind_t;

typedef struct {
    int kind;
    double num;
    char *ident;
    size_t ident_len;
    size_t col_idx;
} dsv_expr_item_t;

typedef struct {
    dsv_expr_item_t *items;
    size_t count;
    int has_operator;
} dsv_expr_output_t;

typedef struct {
    int type;
    const char *value;
    size_t length;
} dsv_expr_token_t;

typedef struct {
    const char *input;
    dsv_expr_output_t out;
    int error;
    char error_msg[256];
} dsv_expr_parse_ctx_t;

void dsv_expr_output_free(dsv_expr_output_t *out);
int dsv_expr_parse(const char *expr, size_t len, dsv_expr_output_t *out, char *error_msg, size_t error_msg_cap);

int dsv_expr_ctx_push_number(dsv_expr_parse_ctx_t *ctx, const char *value, size_t len);
int dsv_expr_ctx_push_ident(dsv_expr_parse_ctx_t *ctx, const char *value, size_t len);
int dsv_expr_ctx_push_op(dsv_expr_parse_ctx_t *ctx, int kind);
void dsv_expr_ctx_set_error(dsv_expr_parse_ctx_t *ctx, const char *msg);

/* Lemon-generated parser entry points (header generated by lemon only exports token ids). */
void *DsvExprParseAlloc(void *(*mallocProc)(size_t));
void DsvExprParse(void *yyp, int yymajor, dsv_expr_token_t yyminor, dsv_expr_parse_ctx_t *ctx);
void DsvExprParseFree(void *p, void (*freeProc)(void *));

#ifdef __cplusplus
}
#endif

#endif
