# Run the real CLI twice per gated schema. A rejection may not replace either
# pre-existing output, and must retain the same schema/type diagnostic.
if(NOT DEFINED TBE_COMPILER OR NOT DEFINED WORK_DIR)
  message(FATAL_ERROR "TBE_COMPILER and WORK_DIR are required")
endif()
file(MAKE_DIRECTORY "${WORK_DIR}")
set(types datetime date time duration decimal bigint money MadeUp union)
foreach(type IN LISTS types)
  if(type STREQUAL "union")
    set(schema "composite Point { int32 x; } union Choice { Point point; } message Gate { Choice value; }")
    set(context "union declarations")
  else()
    set(schema "message Gate { ${type} value; }")
    set(context "Gate[.]value")
  endif()
  file(WRITE "${WORK_DIR}/${type}.schema" "${schema}")
  file(WRITE "${WORK_DIR}/${type}.h" "existing header\n")
  file(WRITE "${WORK_DIR}/${type}.c" "existing source\n")
  foreach(attempt RANGE 1 2)
    execute_process(COMMAND "${TBE_COMPILER}" "${WORK_DIR}/${type}.schema"
      --lang c --output "${WORK_DIR}/${type}.h" --source-output "${WORK_DIR}/${type}.c"
      RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE diagnostic)
    if(result EQUAL 0 OR NOT diagnostic MATCHES "${context}" OR NOT diagnostic MATCHES "${type}")
      message(FATAL_ERROR "${type}: wrong rejection (${result}): ${diagnostic}")
    endif()
    file(READ "${WORK_DIR}/${type}.h" header)
    file(READ "${WORK_DIR}/${type}.c" source)
    if(NOT header STREQUAL "existing header\n" OR NOT source STREQUAL "existing source\n")
      message(FATAL_ERROR "${type}: rejected generation changed caller output")
    endif()
    if(attempt EQUAL 2 AND NOT diagnostic STREQUAL first_diagnostic)
      message(FATAL_ERROR "${type}: rejection diagnostic changed between attempts")
    endif()
    set(first_diagnostic "${diagnostic}")
  endforeach()
endforeach()
message(STATUS "CMeta CLI gates: 9 schemas rejected twice with unchanged outputs")
