/**
 * @file jsonpath_types.h
 * @brief JSONPath parser internal AST types
 */

#ifndef JSONPATH_TYPES_H
#define JSONPATH_TYPES_H

#include <stddef.h>
#include <stdint.h>

/* Internal opcode types that are not lexer terminals. The value must not
 * collide with the JSONPATH_TOKEN_* terminals generated by Lemon (currently
 * 1..28). */
#define JSONPATH_TOKEN_SLICE 100

/* Presence bits for slice selectors: bit set means the corresponding
 * component was written in the expression; unset means it was omitted and the
 * RFC 9535 default (which depends on the step sign) applies at runtime. */
#define JSONPATH_SLICE_HAS_START 0x01u
#define JSONPATH_SLICE_HAS_END   0x02u
#define JSONPATH_SLICE_HAS_STEP  0x04u

#ifdef __cplusplus
extern "C" {
#endif

typedef struct jsonpath_opcode_s {
  int type;
  struct jsonpath_opcode_s *next;
  struct jsonpath_opcode_s *down;
  struct jsonpath_opcode_s *sibling;
  char *str;
  int num;
  int num2;
  int num3;
  uint32_t slice_mask;
  int is_selector; /* bracket/union selector root needing a filter VM program */
  double number;
  size_t compiled_index_plus_one;
} jsonpath_opcode_t;

typedef struct jsonpath_parse_ctx_s {
  jsonpath_opcode_t *pool;
  jsonpath_opcode_t *path;
  int error_pos;
  int error_code;
  int off;
} jsonpath_parse_ctx_t;

jsonpath_opcode_t *jsonpath_append_op(jsonpath_opcode_t *a, jsonpath_opcode_t *b);
jsonpath_opcode_t *jsonpath_alloc_op(jsonpath_parse_ctx_t *ctx, int type, int num,
                                      double number, const char *str, ...);

#ifdef __cplusplus
}
#endif

#endif /* JSONPATH_TYPES_H */
