cmake_minimum_required(VERSION 3.20)

foreach(required_variable IN ITEMS TP_EVIDENCE_DIR TP_CONFIG)
  if(NOT DEFINED ${required_variable} OR "${${required_variable}}" STREQUAL "")
    message(FATAL_ERROR "Missing required variable: ${required_variable}")
  endif()
endforeach()
if(NOT DEFINED TP_EXPECT_FORBIDDEN)
  set(TP_EXPECT_FORBIDDEN OFF)
endif()
if(NOT DEFINED TP_ROOT_TARGETS OR "${TP_ROOT_TARGETS}" STREQUAL "")
  set(TP_ROOT_TARGETS TurboParser::TbeCBind TurboParser::Parser)
endif()

file(STRINGS "${TP_EVIDENCE_DIR}/manifest.txt" manifest_lines)
set(manifest_targets "")
foreach(manifest_line IN LISTS manifest_lines)
  if(NOT manifest_line MATCHES "^([^|]+)[|]([0-9a-f]+)$")
    message(FATAL_ERROR "Malformed dependency evidence manifest: ${manifest_line}")
  endif()
  list(APPEND manifest_targets "${CMAKE_MATCH_1}")
endforeach()

set_property(GLOBAL PROPERTY TBE_CBIND_EVIDENCE_VISITED "")
set_property(GLOBAL PROPERTY TBE_CBIND_EVIDENCE_CLOSURE "")
set_property(GLOBAL PROPERTY TBE_CBIND_EVIDENCE_FORBIDDEN "")

function(verify_evaluated_target target_name dependency_path)
  get_property(visited GLOBAL PROPERTY TBE_CBIND_EVIDENCE_VISITED)
  list(FIND visited "${target_name}" visited_index)
  if(NOT visited_index EQUAL -1)
    return()
  endif()
  set_property(GLOBAL APPEND PROPERTY TBE_CBIND_EVIDENCE_VISITED
    "${target_name}")
  set_property(GLOBAL APPEND PROPERTY TBE_CBIND_EVIDENCE_CLOSURE
    "${target_name}")

  string(TOLOWER "${target_name}" target_lower)
  if(target_lower MATCHES "databind|data_bind")
    set_property(GLOBAL PROPERTY TBE_CBIND_EVIDENCE_FORBIDDEN
      "${dependency_path} -> ${target_name}")
    return()
  endif()

  list(FIND manifest_targets "${target_name}" manifest_index)
  if(manifest_index EQUAL -1)
    return()
  endif()
  string(MD5 evidence_key "${target_name}")
  set(evidence_file
    "${TP_EVIDENCE_DIR}/${evidence_key}-${TP_CONFIG}.txt")
  if(NOT EXISTS "${evidence_file}")
    message(FATAL_ERROR
      "Missing evaluated interface evidence for ${target_name}: ${evidence_file}")
  endif()
  file(READ "${evidence_file}" evaluated_text)
  set(evaluated_dependencies ${evaluated_text})
  foreach(dependency IN LISTS evaluated_dependencies)
    string(STRIP "${dependency}" dependency)
    if("${dependency}" STREQUAL "")
      continue()
    endif()
    string(TOLOWER "${dependency}" dependency_lower)
    if(dependency_lower MATCHES "databind|data_bind")
      set_property(GLOBAL PROPERTY TBE_CBIND_EVIDENCE_FORBIDDEN
        "${dependency_path} -> ${target_name} -> ${dependency}")
      return()
    endif()
    list(FIND manifest_targets "${dependency}" dependency_index)
    if(NOT dependency_index EQUAL -1)
      verify_evaluated_target("${dependency}"
        "${dependency_path} -> ${target_name}")
    endif()
  endforeach()
endfunction()

foreach(root_target IN LISTS TP_ROOT_TARGETS)
  verify_evaluated_target("${root_target}" "root")
endforeach()
get_property(forbidden_path GLOBAL PROPERTY TBE_CBIND_EVIDENCE_FORBIDDEN)
get_property(evaluated_closure GLOBAL PROPERTY TBE_CBIND_EVIDENCE_CLOSURE)
if(DEFINED TP_OUTPUT_FILE AND NOT "${TP_OUTPUT_FILE}" STREQUAL "")
  file(WRITE "${TP_OUTPUT_FILE}" "${evaluated_closure}\n")
endif()

if(NOT "${forbidden_path}" STREQUAL "")
  if(TP_EXPECT_FORBIDDEN)
    message(STATUS "Detected forbidden DataBind dependency: ${forbidden_path}")
    return()
  endif()
  message(FATAL_ERROR "Detected forbidden DataBind dependency: ${forbidden_path}")
endif()
if(TP_EXPECT_FORBIDDEN)
  message(FATAL_ERROR
    "Expected a forbidden DataBind dependency, evaluated closure was: ${evaluated_closure}")
endif()
message(STATUS "Evaluated dependency closure: ${evaluated_closure}")
