function(cyaml_generate_exports HEADER_FILES OUTPUT_DIR)
    set(HEADER_CONTENT "")
    foreach(HEADER_FILE ${HEADER_FILES})
        file(READ "${HEADER_FILE}" CONTENT)
        string(APPEND HEADER_CONTENT "${CONTENT}\n")
    endforeach()
    string(REGEX MATCHALL "CYAML_API [^;(]+\\(" API_MATCHES "${HEADER_CONTENT}")

    set(EXPORT_SYMBOLS "")
    foreach(MATCH ${API_MATCHES})
        string(REGEX REPLACE ".*[ *]([a-zA-Z_][a-zA-Z0-9_]*)\\($" "\\1" FUNC_NAME "${MATCH}")
        if(FUNC_NAME MATCHES "^cyaml_")
            list(APPEND EXPORT_SYMBOLS "${FUNC_NAME}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES EXPORT_SYMBOLS)
    list(SORT EXPORT_SYMBOLS)

    set(DARWIN_CONTENT "")
    foreach(SYM ${EXPORT_SYMBOLS})
        string(APPEND DARWIN_CONTENT "_${SYM}\n")
    endforeach()
    file(WRITE "${OUTPUT_DIR}/exports_darwin.txt" "${DARWIN_CONTENT}")

    set(LINUX_CONTENT "CYAML_1.0 {\n    global:\n")
    foreach(SYM ${EXPORT_SYMBOLS})
        string(APPEND LINUX_CONTENT "        ${SYM};\n")
    endforeach()
    string(APPEND LINUX_CONTENT "    local:\n        *;\n};\n")
    file(WRITE "${OUTPUT_DIR}/exports_linux.map" "${LINUX_CONTENT}")

    set(DEF_CONTENT "LIBRARY cyaml\nEXPORTS\n")
    foreach(SYM ${EXPORT_SYMBOLS})
        string(APPEND DEF_CONTENT "    ${SYM}\n")
    endforeach()
    file(WRITE "${OUTPUT_DIR}/cyaml.def" "${DEF_CONTENT}")

    message(STATUS "Generated exports: ${EXPORT_SYMBOLS}")
endfunction()
