/* Generated by generate_explicit_ec_vectors.py; disposable scalar 7. */
static const struct { const char *private_pem, *public_pem; } explicit_ec_vectors[] = {
  {
    "-----BEGIN EC PRIVATE KEY-----\r\nMIIBaAIBAQQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeggfowgfcC"
    "\r\nAQEwLAYHKoZIzj0BAQIhAP////8AAAABAAAAAAAAAAAAAAAA////////////////\r\nMFsEIP////8AAAABAAAAAAAAAAAA"
    "AAAA///////////////8BCBaxjXYqjqT57Pr\r\nvVV2mIa8ZR0GsMxTsPY7zjw+J9JgSwMVAMSdNgiG5wSTamZ44ROdJreBn3"
    "6QBEEE\r\naxfR8uEsQkf4vOblY6RA8ncDfYEt6zOg9KE5RdiYwpZP40Li/hp/m47n60p8D54W\r\nK84zV2sxXs7LtkBoN79R9Q"
    "IhAP////8AAAAA//////////+85vqtpxeehPO5ysL8\r\nYyVRAgEBoUQDQgAEjlM7b6C/e0YluzBmfAH7YH75+LioD+9bMAYo"
    "cDGHsqNz6x29\r\n4DMYNm0Gn4Om9ZAAU8c2M8sEGyHFXhqGwfQAtA==\r\n-----END EC PRIVATE KEY-----\r\n",
    "-----BEGIN PUBLIC KEY-----\r\nMIIBSzCCAQMGByqGSM49AgEwgfcCAQEwLAYHKoZIzj0BAQIhAP////8AAAABAAAA\r\nAA"
    "AAAAAAAAAA////////////////MFsEIP////8AAAABAAAAAAAAAAAAAAAA////\r\n///////////8BCBaxjXYqjqT57PrvVV2"
    "mIa8ZR0GsMxTsPY7zjw+J9JgSwMVAMSd\r\nNgiG5wSTamZ44ROdJreBn36QBEEEaxfR8uEsQkf4vOblY6RA8ncDfYEt6zOg9K"
    "E5\r\nRdiYwpZP40Li/hp/m47n60p8D54WK84zV2sxXs7LtkBoN79R9QIhAP////8AAAAA\r\n//////////+85vqtpxeehPO5ys"
    "L8YyVRAgEBA0IABI5TO2+gv3tGJbswZnwB+2B+\r\n+fi4qA/vWzAGKHAxh7Kjc+sdveAzGDZtBp+DpvWQAFPHNjPLBBshxV4a"
    "hsH0ALQ=\r\n-----END PUBLIC KEY-----\r\n" },
  {
    "-----BEGIN EC PRIVATE KEY-----\r\nMIIB+gIBAQQwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "\r\nAAAAAAAAAAAHoIIBWzCCAVcCAQEwPAYHKoZIzj0BAQIxAP//////////////////\r\n///////////////////////+////"
    "/wAAAAAAAAAA/////zB7BDD/////////////\r\n/////////////////////////////v////8AAAAAAAAAAP////wEMLMxL6"
    "fiPufk\r\nmI4Fa+P4LRkYHZxu/oFBEgMUCI9QE4daxlY5jYou0Z0qhcjt0+wq7wMVAKM1kmqj\r\nGaJ6HQCJamdzpIJ6zaxzBG"
    "EEqofKIr6LBTeOscce8yCtdG4dO2KLp5uYWfdB4IJU\r\nKjhVAvJdv1UpbDpUXjhydgq3NhfeSpYmLG9dnpi/kpLcKfj0Hb0o"
    "mhR86doxE7Xw\r\nuMAKYLHOHX6BnXpDHXyQ6g5fAjEA////////////////////////////////x2NN\r\ngfQ3Ld9YGg2ySLCn"
    "euzsGWrMxSlzAgEBoWQDYgAEKDwdc2XOR4jyn46/I07f/q1v\r\n6Zf76l/6LVjMnfp7HFCLBVJvVbnrsgQPBbSPttDhlHXJkG"
    "HkG4i6Uu/bjBaQRxph\r\n2GfteZcp2cks0B29IlYw2E7eMqePnmRmTNrFEu+M\r\n-----END EC PRIVATE KEY-----\r\n",
    "-----BEGIN PUBLIC KEY-----\r\nMIIBzDCCAWQGByqGSM49AgEwggFXAgEBMDwGByqGSM49AQECMQD/////////////\r\n//"
    "///////////////////////////v////8AAAAAAAAAAP////8wewQw////////\r\n////////////////////////////////"
    "//7/////AAAAAAAAAAD////8BDCzMS+n\r\n4j7n5JiOBWvj+C0ZGB2cbv6BQRIDFAiPUBOHWsZWOY2KLtGdKoXI7dPsKu8DFQ"
    "Cj\r\nNZJqoxmieh0AiWpnc6SCes2scwRhBKqHyiK+iwU3jrHHHvMgrXRuHTtii6ebmFn3\r\nQeCCVCo4VQLyXb9VKWw6VF44cn"
    "YKtzYX3kqWJixvXZ6Yv5KS3Cn49B29KJoUfOna\r\nMRO18LjACmCxzh1+gZ16Qx18kOoOXwIxAP//////////////////////"
    "////////\r\n/8djTYH0Ny3fWBoNskiwp3rs7BlqzMUpcwIBAQNiAAQoPB1zZc5HiPKfjr8jTt/+\r\nrW/pl/vqX/otWMyd+nsc"
    "UIsFUm9VueuyBA8FtI+20OGUdcmQYeQbiLpS79uMFpBH\r\nGmHYZ+15lynZySzQHb0iVjDYTt4yp4+eZGZM2sUS74w=\r\n----"
    "-END PUBLIC KEY-----\r\n" },
  {
    "-----BEGIN EC PRIVATE KEY-----\r\nMIICngIBAQRCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "\r\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHoIIBxzCCAcMCAQEwTQYHKoZIzj0B\r\nAQJCAf//////////////////////"
    "////////////////////////////////////\r\n////////////////////////////MIGfBEIB//////////////////////"
    "//////\r\n//////////////////////////////////////////////////////////wEQgBR\r\nlT65YY4cmh+SmiGgtoVA7q"
    "LacluZsxXzuLSJkY7xCeFWGTlR7H6TexZSwL07sb8H\r\nNXPfiD0sNPHvRR/Ua1A/AAMVANCeiAApHLhTlsxnFzkyhKqg2mS6"
    "BIGFBADGhY4G\r\ntwQE6c2ePstmI5W0QpxkgTkFP7Uh+CivYGtNPbqhS1537+dZKP4dwSei/6jeM0iz\r\nwYVqQpv5fn4xwuW9"
    "ZgEYOSlqeJo7wARcil+0LH0b2Zj1RElXm0RoF6+9Fyc+ZiyX\r\n7nKZXvQmQMVQuQE/rQdhNTxwhqJywkCIvpR2n9FmUAJCAf"
    "//////////////////\r\n////////////////////////+lGGh4O/L5Zrf8wBSPcJpdA7tcm4iZxHrrtvtx6R\r\nOGQJAgEBoY"
    "GJA4GGAAQAVtXR2Z1bf2NG7rZf2gsHOgxfIuDo9UgyKPAY0sL3EUxd\r\njDCNCr/GmNjJpt8w3OO7xG+VP1D9wmGaAc6tiCgW"
    "7NQAPS0bfZuqoqEQ0dgxejnW\r\nhHi1xYLQKCTw3XHb2Yomy95Va9Dyk83sniuVI6NFkc4aX552cSpd3vx7XGuLyQUl\r\nJRs="
    "\r\n-----END EC PRIVATE KEY-----\r\n",
    "-----BEGIN PUBLIC KEY-----\r\nMIICXTCCAdAGByqGSM49AgEwggHDAgEBME0GByqGSM49AQECQgH/////////////\r\n//"
    "//////////////////////////////////////////////////////////////\r\n/////////zCBnwRCAf//////////////"
    "////////////////////////////////\r\n///////////////////////////////////////8BEIAUZU+uWGOHJofkpohoL"
    "aF\r\nQO6i2nJbmbMV87i0iZGO8QnhVhk5Uex+k3sWUsC9O7G/BzVz34g9LDTx70Uf1GtQ\r\nPwADFQDQnogAKRy4U5bMZxc5Mo"
    "SqoNpkugSBhQQAxoWOBrcEBOnNnj7LZiOVtEKc\r\nZIE5BT+1Ifgor2BrTT26oUted+/nWSj+HcEnov+o3jNIs8GFakKb+X5+"
    "McLlvWYB\r\nGDkpaniaO8AEXIpftCx9G9mY9URJV5tEaBevvRcnPmYsl+5ymV70JkDFULkBP60H\r\nYTU8cIaicsJAiL6Udp/R"
    "ZlACQgH/////////////////////////////////////\r\n//////pRhoeDvy+Wa3/MAUj3CaXQO7XJuImcR667b7cekThkCQ"
    "IBAQOBhgAEAFbV\r\n0dmdW39jRu62X9oLBzoMXyLg6PVIMijwGNLC9xFMXYwwjQq/xpjYyabfMNzju8Rv\r\nlT9Q/cJhmgHOrY"
    "goFuzUAD0tG32bqqKhENHYMXo51oR4tcWC0Cgk8N1x29mKJsve\r\nVWvQ8pPN7J4rlSOjRZHOGl+ednEqXd78e1xri8kFJSUb"
    "\r\n-----END PUBLIC KEY-----\r\n" },
  {
    "-----BEGIN EC PRIVATE KEY-----\r\nMIIBUQIBAQQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeggeMwgeAC"
    "\r\nAQEwLAYHKoZIzj0BAQIhAP////////////////////////////////////7///wv\r\nMEQEIAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAABCAAAAAAAAAAAAAA\r\nAAAAAAAAAAAAAAAAAAAAAAAAAAAABwRBBHm+Zn753LusVaBilc6HCwcCm/"
    "zbLc4o\r\n2VnygVsW+BeYSDradyajxGVdpPv8DhEIqP0XtEimhVQZnEfQj/sQ1LgCIQD/////\r\n///////////////+uq7c5q"
    "9IoDu/0l6M0DZBQQIBAaFEA0IABFy98GRuXbTqo5jz\r\nZfLqeg49QZt+AzDjnOkr3e3KxPm8auvKQLolWWCjF41thhpU26gT"
    "0LgT/ee1pQgm\r\nKAhyZNo=\r\n-----END EC PRIVATE KEY-----\r\n",
    "-----BEGIN PUBLIC KEY-----\r\nMIIBMzCB7AYHKoZIzj0CATCB4AIBATAsBgcqhkjOPQEBAiEA////////////////\r\n//"
    "///////////////////v///C8wRAQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\nAAAAAAAAAAAEIAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAHBEEEeb5m\r\nfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5hIOtp3JqPEZV2k+/wOEQio/R"
    "e0\r\nSKaFVBmcR9CP+xDUuAIhAP////////////////////66rtzmr0igO7/SXozQNkFB\r\nAgEBA0IABFy98GRuXbTqo5jzZf"
    "Lqeg49QZt+AzDjnOkr3e3KxPm8auvKQLolWWCj\r\nF41thhpU26gT0LgT/ee1pQgmKAhyZNo=\r\n-----END PUBLIC KEY---"
    "--\r\n" },
};
