"""Generate disposable interoperability fixtures; cryptography is test tooling only.

The resulting C tests have no Python/OpenSSL runtime dependency. Regenerating
changes random RSA test keys and signatures; never use these public fixtures as keys.
"""
from pathlib import Path
import hashlib
import hmac
import json
import math
from cryptography.hazmat.primitives import hashes, serialization as s
from cryptography.hazmat.primitives.asymmetric import rsa, ec, ed25519, ed448, padding, utils
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

message = b"Salts key interoperability"
out = ['/* Generated by generate_key_vectors.py; disposable public test keys. */',
       'static const struct { int kind, curve, hash; const char *private_pem, *traditional_pem,',
       '  *public_pem, *compressed_pem, *signature, *n, *e, *d, *oaep; } key_vectors[] = {']

def text(data):
    if isinstance(data, bytes):
        data = data.decode()
    return '\n'.join('    ' + json.dumps(data[i:i+96]) for i in range(0, len(data), 96)) or '    ""'

def integer(value):
    return value.to_bytes((value.bit_length()+7)//8, 'big').hex()

keys = [(1, 0, 2, rsa.generate_private_key(65537, 1024))]
large = rsa.generate_private_key(65537, 8192).private_numbers()
exponent = 4294967311  # 33 bits: legacy BoringSSL compatibility boundary.
phi = (large.p-1)*(large.q-1)
assert math.gcd(exponent, phi) == 1
d = pow(exponent, -1, phi)
large = rsa.RSAPrivateNumbers(large.p, large.q, d, d % (large.p-1), d % (large.q-1),
    pow(large.q, -1, large.p), rsa.RSAPublicNumbers(exponent, large.public_numbers.n)).private_key()
keys += [(1, 0, 2, large)]
keys += [(2, i, h, ec.derive_private_key(7, c)) for i,h,c in
         [(1,2,ec.SECP256R1()), (2,3,ec.SECP384R1()), (3,4,ec.SECP521R1()), (4,2,ec.SECP256K1())]]
keys += [(3,0,4,ed25519.Ed25519PrivateKey.from_private_bytes(bytes(range(32)))),
         (4,0,4,ed448.Ed448PrivateKey.from_private_bytes(bytes(range(57))))]
for kind, curve, hash_id, key in keys:
    md = {2: hashes.SHA256(), 3: hashes.SHA384(), 4: hashes.SHA512()}[hash_id]
    private = key.private_bytes(s.Encoding.PEM, s.PrivateFormat.PKCS8, s.NoEncryption())
    traditional = key.private_bytes(s.Encoding.PEM, s.PrivateFormat.TraditionalOpenSSL, s.NoEncryption()) if kind <= 2 else b''
    public = key.public_key().public_bytes(s.Encoding.PEM, s.PublicFormat.SubjectPublicKeyInfo)
    compressed = key.public_key().public_bytes(s.Encoding.X962, s.PublicFormat.CompressedPoint).hex() if kind == 2 else ''
    if kind == 1:
        sig = key.sign(message, padding.PKCS1v15(), md)
        num = key.private_numbers()
        n,e,d = integer(num.public_numbers.n), integer(num.public_numbers.e), integer(num.d)
        oaep = key.public_key().encrypt(b'0123456789abcdef', padding.OAEP(padding.MGF1(md), md, None)).hex()
    elif kind == 2:
        r, v = utils.decode_dss_signature(key.sign(message, ec.ECDSA(md)))
        width = (key.key_size+7)//8
        sig = r.to_bytes(width,'big') + v.to_bytes(width,'big')
        n=e=d=oaep=''
    else:
        sig = key.sign(message)
        n=e=d=oaep=''
    out.append('  { %d, %d, %d,\n%s },' % (kind,curve,hash_id,
        ',\n'.join(text(x) for x in [private,traditional,public,compressed,sig.hex(),n,e,d,oaep])))
out += ['};', 'static const struct { int hash; const char *digest, *mac, *pbkdf2; } symmetric_vectors[] = {']
for ident, name in enumerate(['sha1','sha256','sha384','sha512'], 1):
    out.append('  { %d,\n%s },' % (ident, ',\n'.join(text(x) for x in [
        hashlib.new(name,message).hexdigest(), hmac.new(b'key',message,name).hexdigest(),
        hashlib.pbkdf2_hmac(name,b'password',bytes(range(80)),2,64).hex()])))
out += ['};', 'static const struct { size_t key_size; const char *ciphertext; } gcm_vectors[] = {']
for width in [16,24,32]:
    ciphertext = AESGCM(bytes(range(width))).encrypt(bytes(range(12)),message,b'aad')
    out.append('  { %d, %s },' % (width,text(ciphertext.hex()).strip()))
out += ['};', '']
Path(__file__).with_name('crypto_key_vectors.h').write_text('\n'.join(out))
