"""Regenerate public test fixtures using cryptography (test tooling only).

Private keys in this fixture are disposable test material, never credentials.
The generated C tests run without Python, OpenSSL, or cryptography dependencies.
"""
from pathlib import Path
import argparse
import hashlib
import re
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding, rsa

message = b"Salts RSA provider contract"
cek = bytes(range(32))
path = Path(__file__).with_name("crypto_rsa_vectors.h")
args = argparse.ArgumentParser(description=__doc__)
args.add_argument("--reuse-keys", action="store_true", help="preserve the existing disposable keys")
options = args.parse_args()
existing_keys = []
if options.reuse_keys:
    for encoded in re.findall(r'^  \{\n((?:    "[0-9a-f]+"\n)*    "[0-9a-f]+"),', path.read_text(), re.M):
        data = bytes.fromhex("".join(re.findall(r'"([0-9a-f]+)"', encoded)))
        existing_keys.append(serialization.load_der_private_key(data, password=None))
    if len(existing_keys) not in (3, 4):
        raise ValueError("expected three or four existing private-key fixtures")
lines = [
    "/* Generated by generate_rsa_vectors.py; disposable public test keys. */",
    "static const struct {",
    "  const char *der, *raw;",
    "  const char *signatures[6];",
    "  const char *oaep[2];",
    "  const char *pss_salt_two[3], *oaep_seed_two[2];",
    "  const char *oaep_invalid[5];",
    "} rsa_vectors[] = {",
]


def string(data):
    text = data.hex()
    return "\n".join('    "' + text[i:i+96] + '"' for i in range(0, len(text), 96))


def mgf(seed, size, name):
    result = b""
    counter = 0
    while len(result) < size:
        result += hashlib.new(name, seed + counter.to_bytes(4, "big")).digest()
        counter += 1
    return result[:size]


def xor(a, b):
    assert len(a) == len(b)
    return bytes(x ^ y for x, y in zip(a, b))


def oaep_encode(db, seed, name, leading=0):
    masked_db = xor(db, mgf(seed, len(db), name))
    return bytes([leading]) + xor(seed, mgf(masked_db, len(seed), name)) + masked_db


for index, bits in enumerate((2048, 3072, 4096, 2041)):
    key = existing_keys[index] if index < len(existing_keys) else rsa.generate_private_key(65537, bits)
    if not existing_keys and bits == 3072:
        # Exercise both orderings of the CRT factors.
        n = key.private_numbers()
        key = rsa.RSAPrivateNumbers(n.q, n.p, n.d, n.dmq1, n.dmp1,
                                   pow(n.p, -1, n.q), n.public_numbers).private_key()
    n = key.private_numbers()
    der = key.private_bytes(serialization.Encoding.DER,
                            serialization.PrivateFormat.TraditionalOpenSSL,
                            serialization.NoEncryption())
    size = (bits + 7) // 8
    raw = pow(42, n.d, n.public_numbers.n).to_bytes(size, "big")
    signatures = []
    for pss in (False, True):
        for algorithm in (hashes.SHA256(), hashes.SHA384(), hashes.SHA512()):
            scheme = (padding.PSS(padding.MGF1(algorithm), algorithm.digest_size)
                      if pss else padding.PKCS1v15())
            signatures.append(key.sign(message, scheme, algorithm))
    ciphertexts = [key.public_key().encrypt(cek, padding.OAEP(
        padding.MGF1(algorithm), algorithm, None))
        for algorithm in (hashes.SHA1(), hashes.SHA256())]
    deterministic_pss = []
    deterministic_oaep = []
    # Reference encodings from RFC 8017. The independent cryptography backend
    # verifies/decrypts every valid output before it becomes a C test fixture.
    for algorithm in (hashes.SHA256(), hashes.SHA384(), hashes.SHA512()):
        hlen = algorithm.digest_size
        salt = bytes(hlen - 1) + b"\x02"
        mh = hashlib.new(algorithm.name, message).digest()
        h = hashlib.new(algorithm.name, bytes(8) + mh + salt).digest()
        emlen = (bits - 1 + 7) // 8
        db = bytes(emlen - 2 * hlen - 2) + b"\x01" + salt
        masked = bytearray(xor(db, mgf(h, len(db), algorithm.name)))
        masked[0] &= 0xff >> (8 * emlen - (bits - 1))
        em = bytes(masked) + h + b"\xbc"
        sig = pow(int.from_bytes(em, "big"), n.d, n.public_numbers.n).to_bytes(size, "big")
        key.public_key().verify(sig, message,
            padding.PSS(padding.MGF1(algorithm), hlen), algorithm)
        deterministic_pss.append(sig)
    for algorithm in (hashes.SHA1(), hashes.SHA256()):
        hlen = algorithm.digest_size
        seed = bytes(hlen - 1) + b"\x02"
        db = hashlib.new(algorithm.name).digest() + bytes(size - len(cek) - 2 * hlen - 2) + b"\x01" + cek
        em = oaep_encode(db, seed, algorithm.name)
        ct = pow(int.from_bytes(em, "big"), n.public_numbers.e, n.public_numbers.n).to_bytes(size, "big")
        assert key.decrypt(ct, padding.OAEP(padding.MGF1(algorithm), algorithm, None)) == cek
        deterministic_oaep.append(ct)
    invalid_oaep = []
    hlen = 32
    seed = bytes(hlen - 1) + b"\x02"
    good_db = hashlib.sha256().digest() + bytes(size - len(cek) - 2 * hlen - 2) + b"\x01" + cek
    for variant in range(5):
        db = bytearray(good_db)
        if variant == 0: db[0] ^= 1  # lHash mismatch
        if variant == 1: db[hlen] = 2  # invalid padding before separator
        if variant == 2: db[hlen:] = bytes(len(db) - hlen)  # missing separator
        if variant == 3: db[-len(cek) - 1] = 2  # invalid separator
        em = oaep_encode(bytes(db), seed, "sha256", leading=int(variant == 4))
        ct = pow(int.from_bytes(em, "big"), n.public_numbers.e, n.public_numbers.n).to_bytes(size, "big")
        try:
            key.decrypt(ct, padding.OAEP(padding.MGF1(hashes.SHA256()), hashes.SHA256(), None))
        except ValueError:
            pass
        else:
            raise AssertionError("invalid OAEP fixture accepted")
        invalid_oaep.append(ct)
    lines += ["  {", string(der) + ",", string(raw) + ",", "    {",
              ",\n".join(string(sig) for sig in signatures), "    },", "    {",
              ",\n".join(string(ct) for ct in ciphertexts), "    },", "    {",
              ",\n".join(string(sig) for sig in deterministic_pss), "    },", "    {",
              ",\n".join(string(ct) for ct in deterministic_oaep), "    },", "    {",
              ",\n".join(string(ct) for ct in invalid_oaep), "    }", "  },"]
lines.append("};")
lines.append("#define RSA_VECTOR_COUNT (sizeof(rsa_vectors) / sizeof(rsa_vectors[0]))")
path.write_text("\n".join(lines) + "\n")
