"""Generate public test fixtures with the OpenSSL CLI (test tooling only)."""
from pathlib import Path
import json
import subprocess
from cryptography.hazmat.primitives import serialization as s
from cryptography.hazmat.primitives.asymmetric import ec

lines = ['/* Generated by generate_explicit_ec_vectors.py; disposable scalar 7. */',
         'static const struct { const char *private_pem, *public_pem; } explicit_ec_vectors[] = {']
for curve in [ec.SECP256R1(), ec.SECP384R1(), ec.SECP521R1(), ec.SECP256K1()]:
    key = ec.derive_private_key(7, curve).private_bytes(s.Encoding.PEM,
        s.PrivateFormat.TraditionalOpenSSL, s.NoEncryption())
    values = []
    for extra in [[], ['-pubout']]:
        result = subprocess.run(['openssl','ec','-param_enc','explicit',*extra],
                                input=key, capture_output=True, check=True).stdout.decode()
        values.append('\n'.join('    '+json.dumps(result[i:i+96]) for i in range(0,len(result),96)))
    lines.append('  {\n' + ',\n'.join(values) + ' },')
lines += ['};','']
Path(__file__).with_name('crypto_explicit_ec_vectors.h').write_text('\n'.join(lines))
