"""Generate the offline Unicode 17 name table; never use the host Unicode database."""
import argparse
import hashlib
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCES = {
    "DerivedName.txt": "019758bbe6c756c40fca6d505187ea660c5e195533e2ff2c841963a212c9d369",
    "NameAliases.txt": "793f6f1e4d15fd90f05ae66460191dc4d75d1fea90136a25f30dd6a4cb950eac",
}


def records(filename):
    data = (ROOT / "data" / "17.0.0" / filename).read_bytes()
    if hashlib.sha256(data).hexdigest() != SOURCES[filename]:
        raise ValueError(f"Unicode source hash mismatch: {filename}")
    for line in data.decode("utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            yield [field.strip() for field in line.split(";")]


def generate():
    names, ranges = {}, []
    for filename in SOURCES:
        for fields in records(filename):
            points, name = fields[:2]
            if not re.fullmatch(r"[A-Z0-9 -]+\*?", name):
                raise ValueError(f"Unexpected name alphabet: {name}")
            bounds = [int(value, 16) for value in points.split("..")]
            if name.endswith("*"):
                ranges.append((name[:-1], bounds[0], bounds[-1]))
            else:
                if len(bounds) != 1 or names.get(name, bounds[0]) != bounds[0]:
                    raise ValueError(f"Conflicting name: {name}")
                names[name] = bounds[0]
    lines = ["/* Generated by unicode/tools/generate_names.py. Do not edit.",
             " * Unicode 17.0.0; data license: unicode/data/LICENSE.txt. */",
             f"enum {{ SALTS_UNICODE_MAX_NAME_BYTES = {max(map(len, names))} }};",
             "static const salts_unicode_name_entry salts_unicode_names[] = {"]
    lines.extend(f'  {{"{name}", 0x{scalar:x}u}},' for name, scalar in sorted(names.items()))
    lines.extend(["};", "static const salts_unicode_name_range salts_unicode_name_ranges[] = {"])
    lines.extend(f'  {{"{prefix}", 0x{first:x}u, 0x{last:x}u}},'
                 for prefix, first, last in sorted(ranges))
    lines.extend(["};", ""])
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated data is stale")
    args = parser.parse_args()
    target = ROOT / "src" / "unicode_names_data.h"
    result = generate()
    if args.check:
        if target.read_text(encoding="ascii") != result:
            raise SystemExit("Unicode name table is stale; run unicode/tools/generate_names.py")
    else:
        target.write_text(result, encoding="ascii", newline="\n")
