#!/usr/bin/env python3
"""Generate Unicode 17 word-break property interval tables.

Inputs are Unicode 17.0.0 WordBreakProperty.txt and emoji-data.txt.
The generated header is deterministic and contains no runtime allocation
or mutable state.
"""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

WB_VALUES = {
    "CR": "SALTS_UNICODE_WORD_CR",
    "LF": "SALTS_UNICODE_WORD_LF",
    "Newline": "SALTS_UNICODE_WORD_NEWLINE",
    "Extend": "SALTS_UNICODE_WORD_EXTEND",
    "Format": "SALTS_UNICODE_WORD_FORMAT",
    "ZWJ": "SALTS_UNICODE_WORD_ZWJ",
    "WSegSpace": "SALTS_UNICODE_WORD_WSEG_SPACE",
    "ALetter": "SALTS_UNICODE_WORD_ALETTER",
    "Hebrew_Letter": "SALTS_UNICODE_WORD_HEBREW_LETTER",
    "Numeric": "SALTS_UNICODE_WORD_NUMERIC",
    "Katakana": "SALTS_UNICODE_WORD_KATAKANA",
    "ExtendNumLet": "SALTS_UNICODE_WORD_EXTEND_NUM_LET",
    "MidLetter": "SALTS_UNICODE_WORD_MID_LETTER",
    "MidNum": "SALTS_UNICODE_WORD_MID_NUM",
    "MidNumLet": "SALTS_UNICODE_WORD_MID_NUM_LET",
    "Single_Quote": "SALTS_UNICODE_WORD_SINGLE_QUOTE",
    "Double_Quote": "SALTS_UNICODE_WORD_DOUBLE_QUOTE",
    "Regional_Indicator": "SALTS_UNICODE_WORD_REGIONAL_INDICATOR",
}


def parse_range(text: str) -> tuple[int, int]:
    parts = text.strip().split("..")
    first = int(parts[0], 16)
    last = int(parts[1], 16) if len(parts) == 2 else first
    if first > last or last > 0x10FFFF:
        raise ValueError(f"invalid Unicode range: {text}")
    return first, last


def merge(entries: list[tuple[int, int, str]]) -> list[tuple[int, int, str]]:
    entries.sort()
    result: list[tuple[int, int, str]] = []
    for first, last, value in entries:
        if result and first <= result[-1][1]:
            raise ValueError(f"overlapping Unicode ranges at U+{first:04X}")
        if result and value == result[-1][2] and first == result[-1][1] + 1:
            prev = result[-1]
            result[-1] = (prev[0], last, value)
        else:
            result.append((first, last, value))
    return result


def read(path: Path, marker: str) -> str:
    data = path.read_text(encoding="utf-8")
    if marker not in data[:2048]:
        raise ValueError(f"{path}: expected Unicode marker {marker!r}")
    return data


def records(text: str):
    for raw in text.splitlines():
        payload = raw.split("#", 1)[0].strip()
        if not payload or payload.startswith("@"):
            continue
        yield [part.strip() for part in payload.split(";")]


def parse_word_break(text: str):
    out = []
    for parts in records(text):
        if len(parts) < 2 or parts[1] not in WB_VALUES:
            raise ValueError(f"unknown/malformed Word_Break record: {parts}")
        first, last = parse_range(parts[0])
        out.append((first, last, WB_VALUES[parts[1]]))
    if not out:
        raise ValueError("WordBreakProperty contains no values")
    return merge(out)


def parse_extended_pictographic(text: str):
    out = []
    for parts in records(text):
        if len(parts) < 2:
            raise ValueError(f"malformed emoji-data record: {parts}")
        if parts[1] != "Extended_Pictographic":
            continue
        first, last = parse_range(parts[0])
        out.append((first, last, "1"))
    if not out:
        raise ValueError("emoji-data contains no Extended_Pictographic values")
    return merge(out)


def git_blob_sha(text: str) -> str:
    data = text.encode("utf-8")
    header = f"blob {len(data)}\0".encode("ascii")
    return hashlib.sha1(header + data).hexdigest()


def emit_array(name: str, entries: list[tuple[int, int, str]]) -> list[str]:
    lines = [f"static const salts_unicode_word_range {name}[] = {{"]
    for first, last, value in entries:
        lines.append(f"  {{0x{first:06X}u, 0x{last:06X}u, {value}}},")
    lines.append("};")
    lines.append(f"#define {name.upper()}_COUNT (sizeof({name}) / sizeof({name}[0]))")
    return lines


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--word-break", type=Path, required=True)
    parser.add_argument("--emoji-data", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    wb_text = read(args.word_break, "WordBreakProperty-17.0.0.txt")
    emoji_text = read(args.emoji_data, "Version: 17.0")
    wb = parse_word_break(wb_text)
    ep = parse_extended_pictographic(emoji_text)

    lines = [
        "/* Generated by unicode/tools/generate_word_data.py. DO NOT EDIT. */",
        "/* Unicode 17.0.0 / UAX #29 revision 47. */",
        "/* Sources:",
        f" * WordBreakProperty.txt git blob {git_blob_sha(wb_text)}",
        f" * emoji-data.txt git blob {git_blob_sha(emoji_text)}",
        " * Normative algorithm: UAX #29 revision 47.",
        " */",
        "#ifndef SALTS_UNICODE_WORD_DATA_H",
        "#define SALTS_UNICODE_WORD_DATA_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "typedef struct salts_unicode_word_range {",
        "  uint32_t first;",
        "  uint32_t last;",
        "  uint8_t value;",
        "} salts_unicode_word_range;",
        "",
    ]
    lines += emit_array("salts_unicode_word_break_ranges", wb)
    lines.append("")
    lines += emit_array("salts_unicode_word_extended_pictographic_ranges", ep)
    lines += ["", "#endif", ""]

    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
