#!/usr/bin/env python3
"""Generate Unicode 17 line-break property interval tables.

Input is Unicode 17.0.0 LineBreak.txt. The generated header is deterministic
and contains no runtime allocation or mutable state.
"""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

LB_VALUES = {
    "OP": "SALTS_UNICODE_LINE_BREAK_OP",
    "CL": "SALTS_UNICODE_LINE_BREAK_CL",
    "CP": "SALTS_UNICODE_LINE_BREAK_CP",
    "QU": "SALTS_UNICODE_LINE_BREAK_QU",
    "GL": "SALTS_UNICODE_LINE_BREAK_GL",
    "NS": "SALTS_UNICODE_LINE_BREAK_NS",
    "EX": "SALTS_UNICODE_LINE_BREAK_EX",
    "SY": "SALTS_UNICODE_LINE_BREAK_SY",
    "IS": "SALTS_UNICODE_LINE_BREAK_IS",
    "PR": "SALTS_UNICODE_LINE_BREAK_PR",
    "PO": "SALTS_UNICODE_LINE_BREAK_PO",
    "NU": "SALTS_UNICODE_LINE_BREAK_NU",
    "AL": "SALTS_UNICODE_LINE_BREAK_AL",
    "HL": "SALTS_UNICODE_LINE_BREAK_HL",
    "ID": "SALTS_UNICODE_LINE_BREAK_ID",
    "IN": "SALTS_UNICODE_LINE_BREAK_IN",
    "HY": "SALTS_UNICODE_LINE_BREAK_HY",
    "BA": "SALTS_UNICODE_LINE_BREAK_BA",
    "BB": "SALTS_UNICODE_LINE_BREAK_BB",
    "B2": "SALTS_UNICODE_LINE_BREAK_B2",
    "ZW": "SALTS_UNICODE_LINE_BREAK_ZW",
    "CM": "SALTS_UNICODE_LINE_BREAK_CM",
    "WJ": "SALTS_UNICODE_LINE_BREAK_WJ",
    "H2": "SALTS_UNICODE_LINE_BREAK_H2",
    "H3": "SALTS_UNICODE_LINE_BREAK_H3",
    "JL": "SALTS_UNICODE_LINE_BREAK_JL",
    "JV": "SALTS_UNICODE_LINE_BREAK_JV",
    "JT": "SALTS_UNICODE_LINE_BREAK_JT",
    "RI": "SALTS_UNICODE_LINE_BREAK_RI",
    "EB": "SALTS_UNICODE_LINE_BREAK_EB",
    "EM": "SALTS_UNICODE_LINE_BREAK_EM",
    "ZWJ": "SALTS_UNICODE_LINE_BREAK_ZWJ",
    "AK": "SALTS_UNICODE_LINE_BREAK_AK",
    "AP": "SALTS_UNICODE_LINE_BREAK_AP",
    "AS": "SALTS_UNICODE_LINE_BREAK_AS",
    "VF": "SALTS_UNICODE_LINE_BREAK_VF",
    "VI": "SALTS_UNICODE_LINE_BREAK_VI",
    "HH": "SALTS_UNICODE_LINE_BREAK_HH",
    "CB": "SALTS_UNICODE_LINE_BREAK_CB",
    "AI": "SALTS_UNICODE_LINE_BREAK_AI",
    "BK": "SALTS_UNICODE_LINE_BREAK_BK",
    "CJ": "SALTS_UNICODE_LINE_BREAK_CJ",
    "CR": "SALTS_UNICODE_LINE_BREAK_CR",
    "LF": "SALTS_UNICODE_LINE_BREAK_LF",
    "NL": "SALTS_UNICODE_LINE_BREAK_NL",
    "SA": "SALTS_UNICODE_LINE_BREAK_SA",
    "SG": "SALTS_UNICODE_LINE_BREAK_SG",
    "SP": "SALTS_UNICODE_LINE_BREAK_SP",
    "XX": "SALTS_UNICODE_LINE_BREAK_XX",
}


def parse_range(text: str) -> tuple[int, int]:
    parts = text.strip().split("..")
    first = int(parts[0], 16)
    last = int(parts[1], 16) if len(parts) == 2 else first
    if first > last or last > 0x10FFFF:
        raise ValueError(f"invalid Unicode range: {text}")
    return first, last


def merge(entries: list[tuple[int, int, str]]) -> list[tuple[int, int, str]]:
    entries.sort()
    result: list[tuple[int, int, str]] = []
    for first, last, value in entries:
        if result and first <= result[-1][1]:
            raise ValueError(f"overlapping Unicode ranges at U+{first:04X}")
        if result and value == result[-1][2] and first == result[-1][1] + 1:
            prev = result[-1]
            result[-1] = (prev[0], last, value)
        else:
            result.append((first, last, value))
    return result


def read(path: Path) -> str:
    data = path.read_text(encoding="utf-8")
    if "LineBreak-17.0.0.txt" not in data[:2048]:
        raise ValueError(f"{path}: expected Unicode 17.0.0 LineBreak.txt")
    return data


def records(text: str):
    for raw in text.splitlines():
        payload = raw.split("#", 1)[0].strip()
        if not payload or payload.startswith("@"):
            continue
        yield [part.strip() for part in payload.split(";")]


def parse_line_break(text: str):
    out = []
    for parts in records(text):
        if len(parts) < 2 or parts[1] not in LB_VALUES:
            raise ValueError(f"unknown/malformed Line_Break record: {parts}")
        first, last = parse_range(parts[0])
        out.append((first, last, LB_VALUES[parts[1]]))
    if not out:
        raise ValueError("LineBreak.txt contains no values")
    return merge(out)


def git_blob_sha(text: str) -> str:
    data = text.encode("utf-8")
    header = f"blob {len(data)}\0".encode("ascii")
    return hashlib.sha1(header + data).hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--line-break", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    source = read(args.line_break)
    entries = parse_line_break(source)

    lines = [
        "/* Generated by unicode/tools/generate_line_break_data.py. DO NOT EDIT. */",
        "/* Unicode 17.0.0 / UAX #14 revision 55. */",
        "/* Sources:",
        f" * LineBreak.txt git blob {git_blob_sha(source)}",
        " * Normative algorithm: UAX #14 revision 55.",
        " */",
        "#ifndef SALTS_UNICODE_LINE_BREAK_DATA_H",
        "#define SALTS_UNICODE_LINE_BREAK_DATA_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "typedef struct salts_unicode_line_break_range {",
        "  uint32_t first;",
        "  uint32_t last;",
        "  uint8_t value;",
        "} salts_unicode_line_break_range;",
        "",
        "static const salts_unicode_line_break_range salts_unicode_line_break_ranges[] = {",
    ]
    for first, last, value in entries:
        lines.append(f"  {{0x{first:06X}u, 0x{last:06X}u, {value}}},")
    lines += [
        "};",
        "#define SALTS_UNICODE_LINE_BREAK_RANGES_COUNT \\",
        "  (sizeof(salts_unicode_line_break_ranges) / sizeof(salts_unicode_line_break_ranges[0]))",
        "",
        "#endif",
        "",
    ]
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
