#!/usr/bin/env python3
"""Generate Unicode 17 Bidi_Class interval tables."""
from __future__ import annotations

import argparse
import hashlib
from array import array
from pathlib import Path

VALUE_NAMES = (
    "L R AL EN ES ET AN CS NSM BN B S WS ON "
    "LRE LRO RLE RLO PDF LRI RLI FSI PDI"
).split()
VALUE_TO_ID = {name: i for i, name in enumerate(VALUE_NAMES)}

def parse_range(text: str) -> tuple[int, int]:
    parts = text.strip().split("..")
    first = int(parts[0], 16)
    last = int(parts[1], 16) if len(parts) == 2 else first
    if first > last or last > 0x10FFFF:
        raise ValueError(f"invalid Unicode range: {text}")
    return first, last

def git_blob_sha(text: str) -> str:
    data = text.encode("utf-8")
    return hashlib.sha1(f"blob {len(data)}\0".encode("ascii") + data).hexdigest()

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--derived-bidi-class", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    text = args.derived_bidi_class.read_text(encoding="utf-8")
    if "DerivedBidiClass-17.0.0.txt" not in text[:2048]:
        raise ValueError("expected Unicode 17.0.0 DerivedBidiClass.txt")

    values = array("B", [VALUE_TO_ID["L"]]) * 0x110000

    # Apply UCD @missing defaults in source order. The file starts with the
    # whole-domain L default and then narrows specific unassigned RTL/ET/BN
    # regions. Explicit records below override these defaults.
    for raw in text.splitlines():
        stripped = raw.strip()
        if not stripped.startswith("# @missing:"):
            continue
        payload = stripped[len("# @missing:"):].strip()
        range_text, value_text = [part.strip() for part in payload.split(";", 1)]
        if value_text not in VALUE_TO_ID:
            raise ValueError(f"unknown @missing Bidi_Class: {value_text}")
        first, last = parse_range(range_text)
        values[first:last + 1] = array("B", [VALUE_TO_ID[value_text]]) * (last - first + 1)

    for raw in text.splitlines():
        payload = raw.split("#", 1)[0].strip()
        if not payload:
            continue
        parts = [part.strip() for part in payload.split(";")]
        if len(parts) < 2 or parts[1] not in VALUE_TO_ID:
            raise ValueError(f"unknown/malformed Bidi_Class record: {parts}")
        first, last = parse_range(parts[0])
        values[first:last + 1] = array("B", [VALUE_TO_ID[parts[1]]]) * (last - first + 1)

    ranges: list[tuple[int, int, int]] = []
    start = 0
    current = values[0]
    for scalar in range(1, 0x110000):
        value = values[scalar]
        if value != current:
            ranges.append((start, scalar - 1, current))
            start = scalar
            current = value
    ranges.append((start, 0x10FFFF, current))

    lines = [
        "/* Generated by unicode/tools/generate_bidi_data.py. DO NOT EDIT. */",
        "/* Unicode 17.0.0 / UAX #9 revision 51. */",
        "/* Sources:",
        f" * DerivedBidiClass.txt git blob {git_blob_sha(text)}",
        " * Normative algorithm: UAX #9 revision 51.",
        " */",
        "#ifndef SALTS_UNICODE_BIDI_DATA_H",
        "#define SALTS_UNICODE_BIDI_DATA_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "typedef struct salts_unicode_bidi_range {",
        "  uint32_t first;",
        "  uint32_t last;",
        "  uint8_t value;",
        "} salts_unicode_bidi_range;",
        "",
        "static const salts_unicode_bidi_range salts_unicode_bidi_ranges[] = {",
    ]
    for first, last, value in ranges:
        name = VALUE_NAMES[value]
        lines.append(
            f"  {{0x{first:06X}u, 0x{last:06X}u, SALTS_UNICODE_BIDI_{name}}},"
        )
    lines += [
        "};",
        "#define SALTS_UNICODE_BIDI_RANGES_COUNT (sizeof(salts_unicode_bidi_ranges) / sizeof(salts_unicode_bidi_ranges[0]))",
        "",
        "#endif",
        "",
    ]
    args.output.write_text("\n".join(lines), encoding="utf-8")

if __name__ == "__main__":
    main()
