"""Generate immutable Unicode 17.0.0 full-case tables for salts_unicode."""
from __future__ import annotations

import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "17.0.0"
OUTPUT = ROOT / "src" / "unicode_case_data.h"
CASED = 1
CASE_IGNORABLE = 2


def codepoints(field: str) -> tuple[int, ...]:
    return tuple(int(value, 16) for value in field.split()) if field else ()


def intervals(values: dict[int, int]) -> list[tuple[int, int, int]]:
    result: list[tuple[int, int, int]] = []
    for scalar in sorted(values):
        flags = values[scalar]
        if result and result[-1][2] == flags and scalar == result[-1][1] + 1:
            result[-1] = (result[-1][0], scalar, flags)
        else:
            result.append((scalar, scalar, flags))
    return result


def mapping_table(mapping: dict[int, tuple[int, ...]], label: str) -> str:
    values: list[int] = []
    entries: list[tuple[int, int, int]] = []
    for scalar, mapped in sorted(mapping.items()):
        if mapped == (scalar,):
            continue
        entries.append((scalar, len(values), len(mapped)))
        values.extend(mapped)
    lines = [f"static const uint32_t salts_unicode_{label}_values[] = {{"]
    lines.extend(f"  0x{value:x}u," for value in values)
    lines.append("};")
    lines.append(f"static const salts_unicode_case_mapping salts_unicode_{label}_mappings[] = {{")
    lines.extend(f"  {{0x{scalar:x}u, {offset}u, {length}u}}," for scalar, offset, length in entries)
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    upper: dict[int, tuple[int, ...]] = {}
    lower: dict[int, tuple[int, ...]] = {}
    title: dict[int, tuple[int, ...]] = {}
    for raw in (DATA / "UnicodeData.txt").read_text(encoding="utf-8").splitlines():
        fields = raw.split(";")
        scalar = int(fields[0], 16)
        if fields[12]: upper[scalar] = (int(fields[12], 16),)
        if fields[13]: lower[scalar] = (int(fields[13], 16),)
        if fields[14]: title[scalar] = (int(fields[14], 16),)
    for raw in (DATA / "SpecialCasing.txt").read_text(encoding="utf-8").splitlines():
        data = raw.partition("#")[0].strip()
        if not data:
            continue
        fields = [field.strip() for field in data.split(";")]
        if fields[4]:
            continue
        scalar = int(fields[0], 16)
        lower[scalar] = codepoints(fields[1])
        title[scalar] = codepoints(fields[2])
        upper[scalar] = codepoints(fields[3])
    for scalar, mapped in upper.items():
        title.setdefault(scalar, mapped)
    properties: dict[int, int] = {}
    for raw in (DATA / "DerivedCoreProperties.txt").read_text(encoding="utf-8").splitlines():
        data = raw.partition("#")[0].strip()
        if not data:
            continue
        points, property_name = (field.strip() for field in data.split(";", 1))
        flag = CASED if property_name == "Cased" else CASE_IGNORABLE if property_name == "Case_Ignorable" else 0
        if not flag:
            continue
        bounds = [int(value, 16) for value in points.split("..")]
        for scalar in range(bounds[0], bounds[-1] + 1):
            properties[scalar] = properties.get(scalar, 0) | flag
    files = (DATA / "UnicodeData.txt", DATA / "SpecialCasing.txt", DATA / "DerivedCoreProperties.txt")
    lines = ["/* Generated by unicode/tools/generate_case_data.py. Do not edit.",
             " * Unicode 17.0.0 default full mappings; data license: unicode/data/LICENSE.txt.",
             *(f" * {path.name} SHA-256: {hashlib.sha256(path.read_bytes()).hexdigest()}" for path in files),
             " */", mapping_table(upper, "upper"), mapping_table(lower, "lower"),
             mapping_table(title, "title"),
             "static const salts_unicode_case_property_range salts_unicode_case_properties[] = {"]
    lines.extend(f"  {{0x{first:x}u, 0x{last:x}u, {flags}u}}," for first, last, flags in intervals(properties))
    lines.append("};")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="ascii")


if __name__ == "__main__":
    main()
