#!/usr/bin/env python3
"""Generate Unicode 17 emoji property interval tables."""
from __future__ import annotations

import argparse
import hashlib
from array import array
from pathlib import Path

PROPERTY_FLAGS = {
    "Emoji": "SALTS_UNICODE_PROPERTY_EMOJI",
    "Emoji_Presentation": "SALTS_UNICODE_PROPERTY_EMOJI_PRESENTATION",
    "Emoji_Modifier": "SALTS_UNICODE_PROPERTY_EMOJI_MODIFIER",
    "Emoji_Modifier_Base": "SALTS_UNICODE_PROPERTY_EMOJI_MODIFIER_BASE",
    "Emoji_Component": "SALTS_UNICODE_PROPERTY_EMOJI_COMPONENT",
    "Extended_Pictographic": "SALTS_UNICODE_PROPERTY_EXTENDED_PICTOGRAPHIC",
}
PROPERTY_BITS = {name: 1 << i for i, name in enumerate(PROPERTY_FLAGS)}

def parse_range(text: str) -> tuple[int, int]:
    parts = text.strip().split("..")
    first = int(parts[0], 16)
    last = int(parts[1], 16) if len(parts) == 2 else first
    if first > last or last > 0x10FFFF:
        raise ValueError(f"invalid Unicode range: {text}")
    return first, last

def git_blob_sha(text: str) -> str:
    data = text.encode("utf-8")
    return hashlib.sha1(f"blob {len(data)}\0".encode("ascii") + data).hexdigest()

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--emoji-data", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    text = args.emoji_data.read_text(encoding="utf-8")
    if "Version: 17.0" not in text[:4096]:
        raise ValueError("expected Unicode 17.0 emoji-data.txt")

    values = array("I", [0]) * 0x110000
    seen = set()

    for raw in text.splitlines():
        payload = raw.split("#", 1)[0].strip()
        if not payload:
            continue
        parts = [part.strip() for part in payload.split(";")]
        if len(parts) < 2:
            raise ValueError(f"malformed emoji-data record: {parts}")
        prop = parts[1]
        if prop not in PROPERTY_BITS:
            raise ValueError(f"unknown Unicode emoji property: {prop}")
        seen.add(prop)
        first, last = parse_range(parts[0])
        bit = PROPERTY_BITS[prop]
        for scalar in range(first, last + 1):
            values[scalar] |= bit

    missing = set(PROPERTY_BITS) - seen
    if missing:
        raise ValueError(f"missing emoji properties: {sorted(missing)}")

    ranges: list[tuple[int, int, int]] = []
    start = None
    current = 0
    for scalar, flags in enumerate(values):
        if flags == 0:
            if start is not None:
                ranges.append((start, scalar - 1, current))
                start = None
                current = 0
            continue
        if start is None:
            start = scalar
            current = flags
        elif flags != current:
            ranges.append((start, scalar - 1, current))
            start = scalar
            current = flags
    if start is not None:
        ranges.append((start, 0x10FFFF, current))

    flag_names = list(PROPERTY_FLAGS)
    lines = [
        "/* Generated by unicode/tools/generate_emoji_data.py. DO NOT EDIT. */",
        "/* Unicode 17.0.0 emoji properties. */",
        "/* Sources:",
        f" * emoji-data.txt git blob {git_blob_sha(text)}",
        " */",
        "#ifndef SALTS_UNICODE_EMOJI_DATA_H",
        "#define SALTS_UNICODE_EMOJI_DATA_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "typedef struct salts_unicode_emoji_range {",
        "  uint32_t first;",
        "  uint32_t last;",
        "  uint32_t flags;",
        "} salts_unicode_emoji_range;",
        "",
        "static const salts_unicode_emoji_range salts_unicode_emoji_ranges[] = {",
    ]
    for first, last, flags in ranges:
        names = [
            PROPERTY_FLAGS[name]
            for i, name in enumerate(flag_names)
            if flags & (1 << i)
        ]
        value = " | ".join(names)
        lines.append(f"  {{0x{first:06X}u, 0x{last:06X}u, {value}}},")
    lines += [
        "};",
        "#define SALTS_UNICODE_EMOJI_RANGES_COUNT (sizeof(salts_unicode_emoji_ranges) / sizeof(salts_unicode_emoji_ranges[0]))",
        "",
        "#endif",
        "",
    ]
    args.output.write_text("\n".join(lines), encoding="utf-8")

if __name__ == "__main__":
    main()
